### ISSUE TITLE
Using OAuth2 from the Command Line?

### ISSUE THREAD

**Issue by mekhami** [harvesthq/api#104]
Does the Harvest API support using OAuth2 authentication from the Command line? Both examples I see in the Oauth2 section are browser-oriented.

**Comment by lanej0** [comment]
I guess you could, it would be a pretty difficult task though.  You need to store tokens between requests somewhere and be able to reauthorize when the authorization token expires.  

OAuth2 is more useful in a web application when you don't want to ask a user for their Harvest username and password and store it somewhere.  Basic auth is a much simpler way to go if you're just making simple calls from the command line because you aren't storing somebody's username and password anywhere centrally. Even if you're distributing a set of scripts, the username and password would only ever get stored within a file locally.
