### ISSUE TITLE
Time entries not found after retrieving IDs

### ISSUE THREAD

**Issue by timwhitlock** [harvesthq/api#109]
Hi.
During testing I have a script that empties my harvest account. As part of this I list all time entries against a project and delete them one-by-one. When I use the `id` obtained in each `day_entry` returned from the list I get a 404 for both `GET /daily/show/{id}` and `DELETE /daily/delete/{id}`.

Does this imply the time entry is not found, or the end point is not found? Both seem not to be the case as the entries are freshly obtained from `projects/{id}/entries` and the end point looks right according to the docs.

Is this perhaps due to my permissions? If so it should respond 403, not 404.

**Comment by lanej0** [comment]
Harvest will return a 404 occasionally if you have insufficient permission to do something.  I can't say whether that's specifically the issue here.  Your best bet is to [write in to our support team](https://www.getharvest.com/help/contact) and they can look at the logs for your account to figure out why you're getting an error.

**Comment by timwhitlock** [comment]
Ok fair enough. I'll assume this is the fault an try authenticating as the most privileged user. 
My point stands that the API should not return 404 for permission problems, it slows the process of solving problems when the wrong errors are given,
