### ISSUE TITLE
Bug: creating clients

### ISSUE THREAD

**Issue by tijsdelameillieure** [harvesthq/api#122]
When I'm trying to create a client, it fails.
I looked at my local files, and there I saw that Clients.prototype.create makes a get-call instead of a post.
But when I changes this, I figured out that my app is using some kind of online files, and I cannot change them...

Also a tip that will makes this API a lot easier to use: when creating something (doesn't matter what), I got a Syntax-error back, instead of the created result (SyntaxError: unexpected end of input). It would be a lot easier if I could just get the result of the create back, because now I have to look up what I inserted (get a list, and then check with a loop which item is the right one).

I'm am using the API in NodeJS by the way.

**Comment by lanej0** [comment]
That sounds like an error being returned by Node, not by us.  If you write in to our support team, they can take a look at the logs on your account and see if your request is making it to us (and if so, what the error is), otherwise, your best bet is to follow up with the Node API library: https://github.com/log0ymxm/node-harvest (maybe open an issue there?)
